name: Update Resources

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
      echo Hello World!
      sudo apt-get install gnupg
      wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc
      sudo apt-key add -
