name: Update Resources

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          echo Hello World!
          echo Goodbye World!
